### ISSUE TITLE
can we get on-prem-stable updated?

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/on-prem-builder#134]
I made this change: https://github.com/habitat-sh/builder/commit/f43d461b197a8a45c7a2949ee53cd19541e73576#diff-e83126d470410245720ddb3be8ab1ef7 a few months ago, but it has not made it into an `on-prem-stable` release.  Right now I have had to fork the plan and build it myself.  Further, I had to modify my current on-prem-builder provision scripts to use my version.

I'd like to know if we can set some expectations on how often `on-prem-stable` is updated.  Eventually, I'd like to trust `habitat` origin and not anyone else's version of the builder packages.

**Comment by dmccown** [comment]
@chefsalim Can you confirm we have a new stable version released?

**Comment by chefsalim** [comment]
Done!
