### ISSUE TITLE
Unable to get OAUTH working using Automate and internally generated certs

### ISSUE THREAD

**Issue by csmartini** [habitat-sh/on-prem-builder#152]
We're trying to enable OAUTH for Habitat through Automate. I've followed the steps:
 https://github.com/habitat-sh/on-prem-builder#oauth-application
 https://automate.chef.io/docs/configuration/#setting-up-automate-as-an-oauth-provider-for-builder

For the Automate certificate, I copied the full chain (for our internally issued cert) and appended to the cert.pem that's being used by the builder-api/builder-api-proxy (in this case '/hab/pkgs/core/cacerts/2018.12.05/20190115014206/ssl/cert.pem').

Connection wise everything seems to work. I navigate to habitat and choose to login. Get directed to our Automate instance and login which then takes me back to habitat. But once back there it will time out after about 15 seconds and give me the "DANGER Unable to retrieve oauth token" error.

We saw the open issue https://github.com/habitat-sh/on-prem-builder/issues/33

I set that env variable to the cert.pem listed above but still get the same issue.

I'm not seeing anything logged when using 'journalctl -fu hab-sup'. Please advise on anything else I can try to get this to work. Thanks in advance!
![Capture](https://user-images.githubusercontent.com/51673154/59365136-e2fe5500-8cec-11e9-94e7-260cdbb1ca27.JPG)

**Comment by bdangit** [comment]
I have never been successful with appending my cert chain to cert.pem that has been Habitatized.  If you go the route to setting the `SSL_CERT_FILE` env var, you have to make sure that `hab` user can access the file.  Then make sure to do a full restart of hab-sup and related services.

There is also a way to increase logging on the builder-api so that you can see what is going on.  Check the README.md

**Comment by bdangit** [comment]
https://github.com/habitat-sh/on-prem-builder/blob/master/README.md#debug-logging <- how to enable debug logging

**Comment by csmartini** [comment]
Ok, i'll try adding the hab user to just the internal cert. I tried that once but the install.sh was then failing so hopefully that user trick will get err done.

**Comment by csmartini** [comment]
Ok, debugging logging showed nothing else of note for any of my attempts. Last log was from when the service started.

I gave everyone rwx permissions on the single file then did a 'systemctl restart hab-sup'. Same oauth error.

If I try to do an uninstall/install.sh with just my single file as the "SSL_CERT_FILE", then I get errors during the install around certs like this:
```
☁ Determining latest version of habitat/builder-datastore in the 'on-prem-stable' channel
✗✗✗
✗✗✗ [Err: 0] hab-sup(ER)[components/sup/src/error.rs:465:55]: the handshake failed: The OpenSSL library reported an error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269:: unable to get local issuer certificate
✗✗✗
```
If I set the "SSL_CERT_FILE" back to the the full cert.pem (still with my internal certs appended), I get through the uninstall/install.sh process, but I'm back in the same boat.

**Comment by bdangit** [comment]
Hrmm. Can you look through this ticket? https://github.com/habitat-sh/on-prem-builder/issues/114#issuecomment-455062820

That last comment shows what it finally took to make it work.  I also show a hab-sup systemctl config that should get you more debugging. 

Other thing to try is:

```
SSL_CERT_FILE=/path/to/cert-bundle curl https://<oauth-provider>
```

If that at least works, then there are some configuration issues with hab.

**Comment by csmartini** [comment]
Ok, just read through everything again. I've reverified that I set an env var for SSL_CERT_FILE and that permissions on it and the parent folder are 777.

I've tried setting the variable in a couple different spots as well to make sure I'm covered:
- export SSL_CERT_FILE...
- modifying /etc/environment
- modifying /etc/systemd/system/hab-sup.service

We did notice one additional thing yesterday while doing some more debugging. On the Automate side we were seeing proxy errors. Turns out we needed to add a no_proxy setting there for our internal dns. Should've been there in the first place but this was the first time Automate was doing anything other than hitting our Chef server. Added that and the error went away but still no dice. 

Checking our /hab/svc/builder-api-proyx/logs/host.access.log has this:
```
10.0.174.39 - - [14/Jun/2019:15:44:22 +0000] "GET /v1/authenticate/KUfSOXApmrSThw== HTTP/1.1" 401 0 30.001 "http://habitat.mycorp.com/?state=a1550a19-36cc-46f3-848e-05dcf215b221&code=KUfSOXApmrSThw==" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" - -
```

So still getting a 401 ...

**Comment by csmartini** [comment]
A little more debugging... Spun up a brand new machine and installed again. Same problem. Installed tshark and captured the following during the login session:
```
Jun 14, 2019 12:41:48.186899000 PDT     1       GET     /
Jun 14, 2019 12:41:48.187209000 PDT     1                       200
Jun 14, 2019 12:41:48.231007000 PDT     1       GET     /assets/app-20190406055501.css
Jun 14, 2019 12:41:48.233489000 PDT     2       GET     /habitat.conf.js
Jun 14, 2019 12:41:48.233987000 PDT     2                       200
Jun 14, 2019 12:41:48.241608000 PDT     1                       200
Jun 14, 2019 12:41:48.241651000 PDT     3       GET     /assets/app-20190406055501.js
Jun 14, 2019 12:41:48.368950000 PDT     1       GET     /assets/fonts/titilliumweb-regular.ttf
Jun 14, 2019 12:41:48.399482000 PDT     1                       200
Jun 14, 2019 12:41:48.748176000 PDT     3                       200
Jun 14, 2019 12:41:50.340614000 PDT     3       GET     /assets/images/icons/all.svg
Jun 14, 2019 12:41:50.350096000 PDT     3                       200
Jun 14, 2019 12:41:50.379016000 PDT     3       GET     /assets/images/habitat-logo.svg
Jun 14, 2019 12:41:50.379370000 PDT     3                       200
Jun 14, 2019 12:41:50.381767000 PDT     1       GET     /assets/images/habicat.svg
Jun 14, 2019 12:41:50.382095000 PDT     1                       200
Jun 14, 2019 12:41:50.458540000 PDT     1       GET     /favicon.ico
Jun 14, 2019 12:41:50.459288000 PDT     1                       200
Jun 14, 2019 12:42:00.713241000 PDT     1       GET     /?state=a1550a19-36cc-46f3-848e-05dcf215b221&code=ulFIiYUVEyq3KQ==
Jun 14, 2019 12:42:00.713496000 PDT     1                       200
Jun 14, 2019 12:42:00.768131000 PDT     1       GET     /habitat.conf.js
Jun 14, 2019 12:42:00.768350000 PDT     1                       200
Jun 14, 2019 12:42:02.715501000 PDT     1       GET     /v1/authenticate/ulFIiYUVEyq3KQ==
Jun 14, 2019 12:42:02.715730000 PDT     4       GET     /v1/authenticate/ulFIiYUVEyq3KQ==
Jun 14, 2019 12:42:02.716901000 PDT     5       CONNECT chefautomate.mycorp.com:443
Jun 14, 2019 12:42:32.716333000 PDT     4                       401
Jun 14, 2019 12:42:32.716482000 PDT     1                       401
Jun 14, 2019 12:43:17.700805000 PDT     5                       503
```

So again, looks like the proxy SOMEWHERE isn't getting respected...

**Comment by csmartini** [comment]
Successfully got oauth to work! I had to remove all proxy settings. (i.e. I modified /etc/systemd/system/hab-sup.service and deleted HTTP_PROXY, HTTPS_PROXY, NO_PROXY). Restarted hab-sup and then it all works!

So I'm guessing it's a bug that the authenticate doesn't actually use the NO_PROXY.

**Comment by bdangit** [comment]
Are you setting those env vars when you run the installer?

**Comment by csmartini** [comment]
Correct, we need them so that we can pull down all of the hab packages.

**Comment by chefsalim** [comment]
Great to hear that things are working @csmartini!  I'm going to close this issue for now.

It would be great if you could add a PR to amend the README with any troubleshooting steps that are missing that you found useful.

**Comment by csmartini** [comment]
@chefsalim Hmm, you sure you want to close it? It's still a bug in that the no_proxy env variable isn't getting used.

I'll still follow up on the readme though!
