### ISSUE TITLE
Unable to upload to on prem depot

### ISSUE THREAD

**Issue by abhij22** [habitat-sh/on-prem-builder#163]
Issue Description:
When uploading a package to on-prem depot, `hab pkg upload` reports upload successful. However when I do `hab pkg install` for the same package I get `✗✗✗ [500 Internal Server Error]`

In the bldr logs, I see following error: `ERROR:  bad semver value '201907161907': version number exceeds 31-bit range`

`pkg_version` is computed using `date -u +%Y%m%d%H%m`

**Comment by predominant** [comment]
You might need to change your version number to something parse-able?

Maybe dot notation? `date -u +%Y.%m.%d.%H%m`

**Comment by chefsalim** [comment]
We may also need to update builder-api in the 'on-prem-stable' channel as the newer versions have moved away from a semver library we were using earlier.

**Comment by chefsalim** [comment]
This should be resolved with the new version of builder api that is now on on-prem-stable channel - please uninstall and reinstall your on-prem-builder installation and re-open if it still repros
