### ISSUE TITLE
Document uploading a local package and depdendencies to on prem builder

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/on-prem-builder#178]
# Description
Update documentation on how to seed on prem builder with the packages you need for you application. We need to describe how a user build their application against SaaS Builder and then how to upload that application and it's dependencies to their on prem builder.

We can place this in the on prem builder readme.

# Acceptance Criteria
1. on prem builder readme is updated with an example

**Comment by jeremymv2** [comment]
This has been handled in https://github.com/habitat-sh/on-prem-builder/pull/212
