### ISSUE TITLE
cant download the package

### ISSUE THREAD

**Issue by prashi89** [habitat-sh/on-prem-builder#179]
--> hab-install: Installing Habitat 'hab' program
--> hab-install: Downloading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
xxx hab-install: wget failed to download file, perhaps wget doesn't have SSL support and/or no CA certificates are present?
--> hab-install: Downloading via curl: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
curl: (22) The requested URL returned error: 403
xxx hab-install: curl failed to download file, perhaps curl doesn't have SSL support and/or no CA certificates are present?
xxx hab-install: Required: SSL-enabled 'curl' or 'wget' on PATH with
./hab-sup.service.sh: line 21: hab: command not found

when i verify manually
AZLAPNCHEHAB01 scripts]# curl -L -vv https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
* About to connect() to proxy XXXXXXXXXXXXXXXXXX port 80 (#0)
*   Trying XXXXXXXXXXXXXXXXXXX...
* Connected to XXXXXXXXXXXXXXXX port 80 (#0)
* Establish HTTP proxy tunnel to api.bintray.com:443
> CONNECT api.bintray.com:443 HTTP/1.1
> Host: api.bintray.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.bintray.com
*       start date: Sep 15 00:00:00 2018 GMT
*       expire date: Nov 09 12:00:00 2019 GMT
*       common name: *.bintray.com
*       issuer: CN=GeoTrust RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux HTTP/1.1
> User-Agent: curl/7.29.0
> Host: api.bintray.com
> Accept: */*
>
< HTTP/1.1 302 Found
< Server: nginx
< Date: Wed, 21 Aug 2019 13:57:46 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: https://dl.bintray.com/habitat/stable/linux/x86_64/hab-0.83.0-20190712231625-x86_64-linux.tar.gz?expiry=1566395896499&signature=UUCXh4MHlOlkV5XoBzwBT00D%2F636GKWbF%2FeboZUprdxx6ijQhr8ZwkZwms13s1lJuVZY7NDR2UweZIazNNi7%2Bg%3D%3D
<
* Ignoring the response-body
* Connection #0 to host XXXXXXXXXXXXXXX left intact
* Issue another request to this URL: 'https://dl.bintray.com/habitat/stable/linux/x86_64/hab-0.83.0-20190712231625-x86_64-linux.tar.gz?expiry=1566395896499&signature=UUCXh4MHlOlkV5XoBzwBT00D%2F636GKWbF%2FeboZUprdxx6ijQhr8ZwkZwms13s1lJuVZY7NDR2UweZIazNNi7%2Bg%3D%3D'
* About to connect() to proxy XXXXXXXX port 80 (#1)
*   Trying XXXXXXXXXX
* Connected to XXXXXXXXXXX port 80 (#1)
* Establish HTTP proxy tunnel to dl.bintray.com:443
> CONNECT dl.bintray.com:443 HTTP/1.1
> Host: dl.bintray.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 403 Forbidden
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< Content-Length: 650
<
* Received HTTP code 403 from proxy after CONNECT
* Connection #1 to host XXXXXXXX left intact
curl: (56) Received HTTP code 403 from proxy after CONNECT

**Comment by predominant** [comment]
Can you confirm that you have CA CERTs installed? Looks like at the top its complaining that it has no CA certificates.

**Comment by prashi89** [comment]
i added cert in CA chain file , but still getting error looks something in network proxy level . we are checking that . Thanks for support

**Comment by chefsalim** [comment]
Yes this looks like it may be some network proxy issue.  Please check your proxy settings, and re-open with information on the proxy if this continues to occur. Please also confirm that you can directly download via wget - eg, "wget https://dl.bintray.com/habitat/stable/linux/x86_64/hab-0.83.0-20190712231625-x86_64-linux.tar.gz"
