### ISSUE TITLE
HTTP{S}_PROXY could be in upper or lowercase

### ISSUE THREAD

**Issue by sandratiffin** [habitat-sh/on-prem-builder#180]
In `scripts/hab-sup.service.sh`, Environment settings are configured for the hap-sup service if uppercase HTTP_PROXY/HTTPS_PROXY environment variables are set.

Some apps need these variables to be in lowercase, so the script should look for those and set environment_proxy configs accordingly.

**Comment by predominant** [comment]
@sandratiffin the environment for builder only needs uppercase, as that is what is checked and used within builder. Do you have a debug trace / log showing where you are having issues with proxy environment variables?

**Comment by predominant** [comment]
You're right, some applications accept only upper/lower case. However the environment being populated only checks uppercase. So I feel they should be specified in uppercase.

**Comment by eeyun** [comment]
I agree but its such a trivial fix i've gone ahead and added support to the script.

fixed by #183
