### ISSUE TITLE
On-prem Backup Instructions

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/on-prem-builder#184]
As a user of Habitat Builder I would like concise instructions on how to back-up on-prem builder.

Acceptance Criteria:
- Instructions must cover step-by-step the process to access and back-up builder's database (postgres)
- Instructions must cover step-by-step the process to access and back-up builder's artifact storage (specific to minio)
- Color commentary (even if brief) on automating any backup strategies should be considered an acceptance criteria
- Links to back-up strategies for other backend artifact stores should be included in the instructions (artifactory, AWS s3)

**Comment by predominant** [comment]
A hab package for backups would be ideal.

**Comment by eeyun** [comment]
I think we could pretty easily make a package that runs a backup for the user but i think we should open a second issue for that. Since the services that might need a backup aren't proprietary it should be pretty easy to do both things but in the case of writing a backup package i'd like to talk with some users about how they're leveraging on-prem since there are a few possible deployment architectures!

**Comment by krasnow** [comment]
Closing as this is solved with the Automate installer now.
