### ISSUE TITLE
have a query

### ISSUE THREAD

**Issue by prashi89** [habitat-sh/on-prem-builder#195]
Hi
i am new to this habitat on-premise tool , i installed the on-prem setup using scripts that were provided . but i am looking for the next steps like how can i integrate this with bit bucket and what if the bit bucket in my Org is using SSO logins ? 
is there any other documents to walk through on this ?

**Comment by prashi89** [comment]
i mean i can integrate on-prem with bit-bucket in my organization. but when i click the below link http://locahost/#/pkgs/core it can redirect to bitbucket repository . but after that i cant get on-prem builder UI to create origins

**Comment by chefsalim** [comment]
Hi @prashi89 - it is possible that your OAuth config in bldr.env or the app config in Bitbucket are not correctly configured - please check those settings according to the README. If problems persist please re-open with further details of your configuration and debug logging. You may also want to post questions to the Habitat forum (https://forums.habitat.sh/).

**Comment by prashi89** [comment]
Thanks Salim . what you say is correct and i will also open further for any queries in forum .
