### ISSUE TITLE
how do we know the endpoints for repositories

### ISSUE THREAD

**Issue by prashi89** [habitat-sh/on-prem-builder#204]
for the below section , how do we know the endpoints ? sometimes i face 404 errors . looks like context root is different for each repository setup ? if so , how we can identify the correct endpoints ? 
For the configuration below, you will also need to know following fully qualified end-points:
Authorization Endpoint (example: https://github.com/login/oauth/authorize)
Token Endpoint (example: https://github.com/login/oauth/access_token)
API Endpoint (example: https://api.github.com/user)

**Comment by prashi89** [comment]
why i am asking is for userinfo url, if i use different ones i am getting different error

 hab[11378]: builder-api.default(O): [2019-10-11T07:00:53Z DEBUG reqwest::async_impl::response] Response: '403 Forbidden' for https://gitlab.xxx.xxxx.xxx/api/v4/user
 hab[11378]: builder-api.default(O): [2019-10-11T07:00:53Z DEBUG tokio_reactor::registration] scheduling Read for: 0
 hab[11378]: builder-api.default(O): [2019-10-11T07:00:53Z DEBUG oauth_client::gitlab] GitLab response body: {"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"read_user api"}
 hab[11378]: builder-api.default(O): [2019-10-11T07:00:53Z INFO  actix_web::middleware::logger] 10.xxx.xxx.xx:50494 "GET /v1/authenticate/7d04d7513d1f3391aad9efbe4eb37ddcfc479b40339547fbbc26eae0f8677b9c HTTP/1.1" 401 0 "http://10.XXX.XXXX.XXXX/?code=7d04d7513d1f3391aad9efbe4eb37ddcfc479b40339547fbbc26eae0f8677b9c&state=8e721445-382a-4193-bfd7-3bce8fa4d5f3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" 1.134844




 hab[11378]: builder-api.default(O): [2019-10-11T07:04:08Z DEBUG reqwest::async_impl::response] Response: '401 Unauthorized' for https://gitlab.xxxx.xxx.xxx/vasiredp
 hab[11378]: builder-api.default(O): [2019-10-11T07:04:08Z DEBUG tokio_reactor::registration] scheduling Read for: 0
 hab[11378]: builder-api.default(O): [2019-10-11T07:04:08Z DEBUG oauth_client::gitlab] GitLab response body: {"error":"You need to sign in or sign up before continuing."}
 hab[11378]: builder-api.default(O): [2019-10-11T07:04:08Z INFO  actix_web::middleware::logger] 10.xxx.xxx.xx:51310 "GET /v1/authenticate/372a39bd831655b4a8c46a397d9aee2bd6f86408f4892ad1a3a157f5794e409c HTTP/1.1" 401 0 "http://10.XXX.XXXX.XXXXX/?code=372a39bd831655b4a8c46a397d9aee2bd6f86408f4892ad1a3a157f5794e409c&state=8e721445-382a-4193-bfd7-3bce8fa4d5f3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" 1.138843

**Comment by prashi89** [comment]
does the on-prem builder will allow scope as OpenID to gitlab ? 
because in gitlab application settings even though i selected openid it is throwing me scope error . looks like my gitlab will support only openid.

**Comment by chefsalim** [comment]
Hi @prashi89 - the gitlab auth provider does not allow openid scope currently. In order to determine the endpoints, you will need to work with your local system admin for those services in your enterprise.
