### ISSUE TITLE
Install script has some breakage on the sudo -E commands...

### ISSUE THREAD

**Issue by bdausses** [habitat-sh/on-prem-builder#216]
Reporting an issue with the on-prem-builder install script.  

OS:  chef-highperf-centos7-201910072239

The install script fails here:

```[centos@ip-172-31-20-207 on-prem-builder]$ echo y | sudo -E ./install.sh
IMPORTANT NOTICE

Please review the README at the following location before proceeding!

https://github.com/habitat-sh/on-prem-builder

The following migrations may be required:

For installations prior to June 15, 2018:
* Package migration from file system to Minio store

For installations prior to August 17, 2018
* Database migration to merge shards

For installations prior to September 24th, 2018
* Database merge to a single 'builder' database

Further details can be found in the README.

CHEF END USER LICENSE AGREEMENT

Use of this distribution of Habitat is subject to the terms and conditions of the Chef End User License Agreement. You can find the latest copy of the agreement here:

https://www.chef.io/end-user-license-agreement

./install.sh: line 7: -E: command not found
./hab-sup.service.sh: line 30: hab: command not found
Created symlink from /etc/systemd/system/default.target.wants/hab-sup.service to /etc/systemd/system/hab-sup.service.
```
☝️ This one then will hang at this point until you break out of it.

Using an AmazonLinux 2 AMIl, the `./install.sh: line 7: -E: command not found` error still shows up, but it doesn't stop the install the same way that it does on the chef-highperf-centos7 image...  I'll also note that I saw this at a customer site last Friday too where they are using an internal image based off of Oracle Linux 7.

**Comment by jeremymv2** [comment]
@bdausses sorry for the inconvenience. This issue is closed by the fix in https://github.com/habitat-sh/on-prem-builder/pull/218

**Comment by bdausses** [comment]
@jeremymv2 Thanks for the quick action on this one!!
