### ISSUE TITLE
New bootstrap method fails on "core_full_x86_64-linux_stable" package seed list.

### ISSUE THREAD

**Issue by bdausses** [habitat-sh/on-prem-builder#217]
Attempting to bootstrap a new on-prem-builder install.  Following the new bootstrapping method, the command I am using is:
```
hab pkg download --target x86_64-linux --channel stable --file package_seed_lists/core_full_x86_64-linux_stable --download-directory builder_bootstrap
```

This downloads some of the packages, but then fails with:
```
∵ Missing Error fetching archive core/jdk8/8u92/20160620143238 for x86_64-linux
✗✗✗
✗✗✗ We tried 5 times but could not download core/jdk8/8u92/20160620143238 for x86_64-linux. Last error was: description() is deprecated; use Display
✗✗✗
```
Re-running it seems to download some more packages (but skips ones that it has already downloaded), but then bombs out at the same jdk8 package again.

As a side note...  I tried `core_deps_x86_64-linux_stable` after this failed, and that appeared to work.

OS is the chef-highperf-centos7 AMI.

**Comment by markan** [comment]
Reproduced this locally.

**Comment by markan** [comment]
Looks like spring-petclinic is the culprit. https://bldr.habitat.sh/#/pkgs/core/spring-petclinic/4.2.6/20160824210913

**Comment by markan** [comment]
The latest stable version of core/spring-petclinic for target
x86_64-linux resolves to core/spring-petclinic/4.2.6/20160824210913

The transitive deps (full version below) include
core/jdk8/8u92/20160620143238 which does not exist on builder.

Removing this dep fixes the issue, but arguably we should not have
'impossible' deps in something in stable.

Full TDEPS for reference:
```
core/acl/2.2.52/20160612075215
core/attr/2.4.47/20160612075207
core/cacerts/2016.04.20/20160612081125
core/coreutils/8.25/20160729192409
core/gawk/4.1.3/20160729192843
core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/gmp/6.1.0/20160612064724
core/grep/2.22/20160729192643
core/inetutils/1.9.4/20160729192802
core/jdk8/8u92/20160620143238
core/jre8/8u102/20160729190435
core/libcap/2.24/20160612075226
core/linux-headers/4.3/20160612063537
core/mpfr/3.1.4/20160612064810
core/mysql/5.7.14/20160812153521
core/ncurses/6.0/20160612075116
core/openssl/1.0.2h/20160729194249
core/pcre/8.38/20160729192620
core/procps-ng/3.3.11/20160612075316
core/sed/4.2.2/20160612075228
core/tomcat8/8.5.4/20160824210409
core/zlib/1.2.8/20160612064520

**Comment by bdausses** [comment]
I've verified #219 solves this issue.  Thanks for the quick action on this one.

**Comment by smacfarlane** [comment]
Removing the dep is the correct fix,  that was a demo app from the early days of the project that has been removed from the core origin and is no longer built.
