### ISSUE TITLE
On-prem provisioning should support cloud backend services.

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/on-prem-builder#237]
The builder API is written to be  able to safely (and easily!) consume cloud native SaaS services for its artifact storage and database use. In fact, running a builder cluster using, for example, AWS S3 and AWS RDS is always going to be a preferable experience for our users when it comes to Disaster Recovery and High-Availability.

We should modify our scripts (and in a couple places, at least, tweak our docs) to support users that want to run builder in this configuration.

**Comment by jeremymv2** [comment]
Added in #241
