### ISSUE TITLE
On-prem provisioning script should be front-end aware 

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/on-prem-builder#238]
The builder APIs we deploy are designed to be horizontally scalable for ourselves and users that need the features (in the case of expanded availability). However, our on-prem scripts, don't support this awareness in their deployment pattern. 

We should, as an example, include the ability for the script to deploy a new front end node separate from a backend, OR the ability to deploy multiple front-end nodes.

**Comment by jeremymv2** [comment]
Closed by https://github.com/habitat-sh/on-prem-builder/pull/243
