### ISSUE TITLE
bootstrap-bundle fails when backed by RDS and S3.

### ISSUE THREAD

**Issue by scottvidmar** [habitat-sh/on-prem-builder#248]
OS: Amazon Linux
Utility: install.sh --generate-bootstrap
Setup: RDS-backed, S3-backed
Description of Problem:
We are seeing a failure to copy a pwfile when trying to generate a front-end bundle for Builder. The builder is installed leveraging AWS RDS and AWS S3 instead of stand-alone Postgres and/or Minio.

Output:
```
./install.sh --generate-bootstrap
IMPORTANT NOTICE
Please review the README at the following location before proceeding!
https://github.com/habitat-sh/on-prem-builder
The following migrations may be required:
For installations prior to June 15, 2018:
* Package migration from file system to Minio store
For installations prior to August 17, 2018
* Database migration to merge shards
For installations prior to September 24th, 2018
* Database merge to a single 'builder' database
Further details can be found in the README.
CHEF END USER LICENSE AGREEMENT
Use of this distribution of Habitat is subject to the terms and conditions of the Chef End User License Agreement. You can find the latest copy of the agreement here:
https://www.chef.io/end-user-license-agreement
Do you accept the terms of this license? Answering yes will proceed with the installation. [y/N] y
Generating frontend bootstrap bundle
cp: cannot stat '/hab/svc/builder-datastore/config/pwfile': No such file or directory
```

I think the flow ends up being:
https://github.com/habitat-sh/on-prem-builder/blob/4c9d2ed95ec9529b6eb0dd2e83eadc37aa0ba79f/scripts/provision.sh#L420 starts the entry point to the front-end bundle method -> https://github.com/habitat-sh/on-prem-builder/blob/4c9d2ed95ec9529b6eb0dd2e83eadc37aa0ba79f/scripts/provision.sh#L298  -> https://github.com/habitat-sh/on-prem-builder/blob/4c9d2ed95ec9529b6eb0dd2e83eadc37aa0ba79f/scripts/provision.sh#L310 exits the control block and errors out on trying to move that pwfile

I believe the fix requires that copy statement move into the control block, but the control block also should handle the RDS+S3 permutations along the lines of the configure method: https://github.com/habitat-sh/on-prem-builder/blob/4c9d2ed95ec9529b6eb0dd2e83eadc37aa0ba79f/scripts/provision.sh#L54

**Comment by scottvidmar** [comment]
After talking with other folks, this isn't really necessary, if setting up a new installation or if the install is already setup with RDS and S3. In that case, scaling horizontally doesn't require a frontend-bundle, but shuffling the bldr-frontend.env to the new frontends and installing will work.

At this point, it looks like the documentation around this needs to be updated.

**Comment by mwrock** [comment]
closing since we no longer need the bootstrap bundle
