### ISSUE TITLE
Support Chef Server OpenID Connect as an oauth provider

### ISSUE THREAD

**Issue by mattlqx** [habitat-sh/on-prem-builder#50]
We're using Bitbucket Server which doesn't support being used as an oauth provider. It seems like a good pairing to be able to use Chef Server as an oauth source for Habitat as most users will likely be in common between the two and Chef Server already has the capabilities to server as an oauth provider and be backed by a directory service like LDAP.

**Comment by chefsalim** [comment]
This looks like it is less of a priority from a field perspective atm, so closing for now.

**Comment by bsheltonihs** [comment]
From an truly **air gapped** network/datacenters like we have and not having any of the supported oauth providers available (even though a proxy) this is one of the only things that will make it usable for us. By air gapped I mean put it on disk have the disk scanned and then put on the network. From a customer prospective we have very limited ability to stand up an oauth provider that is currently supported by habitat so with the use of A2 or Chef Server we would be able to use it. 

I would ask that this issue be reevaluated and possibly be opened.
