### ISSUE TITLE
On premise bitbucket setup

### ISSUE THREAD

**Issue by lfillmore** [habitat-sh/on-prem-builder#53]
The on premise bitbucket uses application links. I've managed to get a semiworking application link but the on premise builder just dumps me and leaves me at the bitbucket page. 
I'm assuming it should see I'm already logged into bitbucket and redirect back to the builder. It's not doing that.

**Comment by chefsalim** [comment]
@lfillmore It's not clear that the on-premise Bitbucket will respect / redirect for general OAuth usage - if we're not able to get a redirect from Bitbucket then we can't proceed with the auth workflow. I've updated the README to call out the support for Bitbucket is for the cloud instance.
