### ISSUE TITLE
on-prem-archive.sh behaves unexpectedly when using self-signed cert

### ISSUE THREAD

**Issue by danielcbright** [habitat-sh/on-prem-builder#67]
When setting the `env` variable `SSL_CERT_FILE=/path/to/cert.crt` on a Centos 7 box, and then running the `populate-depot` script, I get the following error:

```
[root@hab-depot on-prem-builder]# ./scripts/on-prem-archive.sh populate-depot https://hab-depot.dbright.com
Fetching latest package bootstrap file.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Cleaning up.
Done.
```

The workaround was to edit the file and add `--insecure` to this [line](https://github.com/habitat-sh/on-prem-builder/blob/master/scripts/on-prem-archive.sh#L91). It would be nice if the script detected the `SSL_CERT_FILE` variable and added the `--insecure` automatically, or allowed you to do so via a CLI option.

**Comment by baumanj** [comment]
Thanks for this, @danielcbright. In the slack discussion, you mentioned

> I got past the SSL error by exporting `SSL_CERT_FILE` from within the `on-prem-archive.sh` script, it seems that the `do` loop in the script isn't honoring env variables for some reason

Can you elaborate? Which loop in particular are you talking about and how did the behavior diverge from your expectations?

**Comment by danielcbright** [comment]
Hey @baumanj I think we can safely ignore my comment there, it seems my original export was missing a `.` for a filename. One of those "I didn't see it until the end" things, I had fixed it by adding `SSL_CERT_FILE=path/to/cert/file.crt ` in front of the `hab` command on [line](https://github.com/habitat-sh/on-prem-builder/blob/master/scripts/on-prem-archive.sh#L272).

For future reference if anyone runs into it, if you don't have that set properly, you'll get this error:

```
✗✗✗
✗✗✗ the handshake failed: The OpenSSL library reported an error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269:: self signed certificate
✗✗✗
```

Which is the same error you'll get if you don't set `SSL_CERT_FILE` at all and you are pointing to a Hab Depot node that has a self-signed SSL cert.

**Comment by eeyun** [comment]
We have another tracking issue around self-signed certs. Since you're unblocked I'm going to go ahead and close this one for now! If you have concerns about that, feel free to reopen!
