### ISSUE TITLE
ANALYTICS_WRITE_KEY: unbound variable

### ISSUE THREAD

**Issue by predominant** [habitat-sh/on-prem-builder#70]
```
✓ Installed core/ncurses/6.0/20170513213009
✓ Installed core/pcre/8.38/20170513213423
✓ Installed core/perl/5.22.1/20170513213942
✓ Installed core/postgresql/9.6.8/20180426174635
✓ Installed core/proj/4.9.3/20171025112633
✓ Installed core/readline/6.3.8/20170513213506
✓ Installed habitat/builder-datastore/7311/20180426183913
★ Install of habitat/builder-datastore/7311/20180426183913 complete with 20 new packages installed.
The habitat/builder-datastore service was successfully loaded
./provision.sh: line 52: ANALYTICS_WRITE_KEY: unbound variable
```

Causes install to fail / stop here.

**Comment by predominant** [comment]
This failed on 1st run with analytics disabled, but worked on 2nd run with analytics enabled.

**Comment by chrisortman** [comment]
I had to set all of those ANALYTICS* variables to "" in order to make it work.
`ANALYTICS_COMPANY_ID=""`

My guess it has to do with version of bash?

**Comment by wduncanfraser** [comment]
Looks like it's just an error in the provision.sh script logic. Goes off without a hitch if ANALYTICS is enabled. If disabled, it's trying to template into the builder-api user.toml config a variable that hasn't been defined.

**Comment by wduncanfraser** [comment]
I believe this was resolved, and is no longer an issue.

**Comment by chefsalim** [comment]
Please reopen if this reoccurs
