### ISSUE TITLE
Error binlinking aws-cli 

### ISSUE THREAD

**Issue by chrisortman** [habitat-sh/on-prem-builder#73]
It conflicts because there is already a python install (RHEL7) and it can't overwrite easy_install

**Comment by wduncanfraser** [comment]
Related to this, with CentOS 7 the binlinking went through without a hitch, but because it binlinked all the deps, it breaks YUM and other system tools that are expecting to call the system python2.

**Comment by jkerry** [comment]
This totally wrecks the system agents in Azure too

**Comment by fnichol** [comment]
I'm curious which version of Habitat y'all are running? We made some fixes in the [0.56.0](https://github.com/habitat-sh/habitat/tree/0.56.0) release so I want to rule that out first.

**Comment by wduncanfraser** [comment]
@fnichol The builder install script defaults to latest, so I've been running into this with 0.59. It looks like the root cause is doing a `hab pkg install -bf core/aws-cli` vs `hab pkg binlink core/aws-cli -f aws` in provision.sh as can be seen in #75 .

**Comment by fnichol** [comment]
Ah, that's a good piece of information--and I like that fix too!

Having said that, we should still try to fix any possible binlinking logic issues.

**Comment by chrisortman** [comment]
I think on the aws image that the terraform scripts are using there is a system supplied /usr/bin/aws

**Comment by HT154** [comment]
Piling on these because I ran into it recently as well. Binlinking all of core/aws-cli breaks yum on enterprise linux, which in turn broke a bunch of our chef cookbooks.
