### ISSUE TITLE
windows-service package is missing from archive  

### ISSUE THREAD

**Issue by TheLunaticScripter** [habitat-sh/on-prem-builder#94]
When running the popluate-depot command as part of the on-prem-archive.sh script it is successful but the `core/windows-service` package is missing form the archive. This is a critical package as it is the `hab-launcher` wrapper for windows.

**Comment by chefsalim** [comment]
We uploaded a new archive with all updated packages on Oct 10th, please re-try and re-open if this is still an issue.

**Comment by smacfarlane** [comment]
core/windows-services still appears to still be missing from the LATEST.tar.gz as of 2019.07.22
